Fix test for DumpPackageTask kotlin class
https://stackoverflow.com/questions/31471880/java-lang-verifyerror-creating-a-gradle-task-with-kotlin

Spek test failure wasn't giving 2nd level of exception:
org.gradle.api.GradleException: Could not generate a proxy class for class at.phatbl.swiftpm.tasks.DumpPackageTask.
	at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:219)
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.model.internal.asm.AsmClassGenerator.define(AsmClassGenerator.java:61)
	at org.gradle.model.internal.asm.AsmClassGenerator.define(AsmClassGenerator.java:56)
	at org.gradle.api.internal.AsmBackedClassGenerator$ClassBuilderImpl.generate(AsmBackedClassGenerator.java:947)
	at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:217)
	... 56 more